### ISSUE TITLE
curator page - error creating DataCite XML 

### ISSUE THREAD

**Issue by sicordero** [usap-dc-dev/usap-dc-website#11]
Could be a problem specific to this dataset because it is a field report? Screenshot attached. Error text copy & pasted below. 

This occurred on dataset [601669](https://www.usap-dc.org/curator?uid=601669), but did not occur on [601668](https://www.usap-dc.org/curator?uid=601668). Both of which are field reports submitted by the same person.

> Traceback (most recent call last): File "/web/usap-dc/htdocs/lib/curatorFunctions.py", line 147, in getDataCiteXML xml = minidom.parseString(res['datacitexml']) File "/usr/lib64/python3.9/xml/dom/minidom.py", line 1998, in parseString return expatbuilder.parseString(string) File "/usr/lib64/python3.9/xml/dom/expatbuilder.py", line 925, in parseString return builder.parseString(string) File "/usr/lib64/python3.9/xml/dom/expatbuilder.py", line 223, in parseString parser.Parse(string, True) xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 1968 During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/web/usap-dc/htdocs/usap.py", line 3242, in curator datacite_file, status = cf.getDataCiteXML(uid) File "/web/usap-dc/htdocs/lib/curatorFunctions.py", line 150, in getDataCiteXML out_text = "Error running database query. \n%s" % sys.exc_info()[1][0] TypeError: 'ExpatError' object is not subscriptable

**Comment by sicordero** [comment]
@fnitsche2001 solved this! There was a strange character in the ISO file.
