### ISSUE TITLE
Python Error on GZIP Upload

### ISSUE THREAD

**Issue by astrong-ldeo** [usap-dc-dev/usap-dc-website#31]
When trying to create SQL and Readme for submission 601711, get this error message:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request rv = self.dispatch_request()
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/web/usap-dc/htdocs/usap.py", line 3062, in curator sql, readme_file = json2sql.json2sql(json_data, uid, curator_id)
File "/web/usap-dc/htdocs/lib/json2sql.py", line 853, in json2sql sql = make_sql(data, id, curator)
File "/web/usap-dc/htdocs/lib/json2sql.py", line 388, in make_sql sql_file_info = get_file_info(id, url, data['upload_directory'], False)
File "/web/usap-dc/htdocs/lib/curatorFunctions.py", line 2784, in get_file_info u_file_size = get_uncompressed_size(path_name)
File "/web/usap-dc/htdocs/lib/curatorFunctions.py", line 2655, in get_uncompressed_size fileobj.seek(-8, 2) io.UnsupportedOperation: can't do nonzero end-relative seeks
```

**Comment by astrong-ldeo** [comment]
May just have to read the file as a binary file instead of regular text file. Will look into other solutions.

**Comment by sicordero** [comment]
New dataset submission (601718) with this issue - is there currently a workaround?
![image](https://github.com/usap-dc-dev/usap-dc-website/assets/83235393/ff97d2b3-641f-4c5f-aa1d-2670c3ce7f6e)

**Comment by astrong-ldeo** [comment]
Yes, extract the files and upload them in another format. Regular ZIP works fine.

**Comment by astrong-ldeo** [comment]
Testing fix in dev. PR #39

**Comment by astrong-ldeo** [comment]
Merged, so I'll close after some confirmation from others that it's working with real prod data sets.
